import { EnumTypeCard, type ICard } from '@/types/card.types'

export const CARDS: ICard[] = [
  {
    name: '1-1-2_1',
    mana: 1,
    attack: 1,
    health: 2,
    imageUrl: '/assets/cards/1-1-2_1.png',
  },
  {
    name: '1-1-2',
    mana: 1,
    attack: 1,
    health: 2,
    imageUrl: '/assets/cards/1-1-2.png',
  },
  {
    name: '1-1-3',
    mana: 1,
    attack: 1,
    health: 3,
    imageUrl: '/assets/cards/1-1-3.png',
  },
  {
    name: '2-1-4',
    mana: 2,
    attack: 1,
    health: 4,
    imageUrl: '/assets/cards/2-1-4.png',
  },
  {
    name: '2-2-1',
    mana: 2,
    attack: 2,
    health: 1,
    imageUrl: '/assets/cards/2-2-1.png',
  },
  {
    name: '2-2-2_1',
    mana: 2,
    attack: 2,
    health: 2,
    imageUrl: '/assets/cards/2-2-2_1.png',
  },
  {
    name: '2-2-2',
    mana: 2,
    attack: 2,
    health: 2,
    imageUrl: '/assets/cards/2-2-2.png',
  },
  {
    name: '2-2-3_1',
    mana: 2,
    attack: 2,
    health: 3,
    imageUrl: '/assets/cards/2-2-3_1.png',
  },
  {
    name: '2-2-3',
    mana: 2,
    attack: 2,
    health: 3,
    imageUrl: '/assets/cards/2-2-3.png',
  },
  {
    name: '2-3-2_1',
    mana: 2,
    attack: 3,
    health: 2,
    imageUrl: '/assets/cards/2-3-2_1.png',
  },
  {
    name: '2-3-2',
    mana: 2,
    attack: 3,
    health: 2,
    imageUrl: '/assets/cards/2-3-2.png',
  },
  {
    name: '3-2-1_1',
    mana: 3,
    attack: 2,
    health: 1,
    imageUrl: '/assets/cards/3-2-1_1.png',
  },
  {
    name: '3-2-1',
    mana: 3,
    attack: 2,
    health: 1,
    imageUrl: '/assets/cards/3-2-1.png',
  },
  {
    name: '3-2-2_1',
    mana: 3,
    attack: 2,
    health: 2,
    imageUrl: '/assets/cards/3-2-2_1.png',
  },
  {
    name: '3-2-2',
    mana: 3,
    attack: 2,
    health: 2,
    imageUrl: '/assets/cards/3-2-2.png',
  },
  {
    name: '3-2-4',
    mana: 3,
    attack: 2,
    health: 4,
    imageUrl: '/assets/cards/3-2-4.png',
  },
  {
    name: '3-3-1',
    mana: 3,
    attack: 3,
    health: 1,
    imageUrl: '/assets/cards/3-3-1.png',
  },
  {
    name: '3-3-3_1',
    mana: 3,
    attack: 3,
    health: 3,
    imageUrl: '/assets/cards/3-3-3_1.png',
  },
  {
    name: '3-3-3',
    mana: 3,
    attack: 3,
    health: 3,
    imageUrl: '/assets/cards/3-3-3.png',
  },
  {
    name: '3-3-4',
    mana: 3,
    attack: 3,
    health: 4,
    imageUrl: '/assets/cards/3-3-4.png',
  },
  {
    name: '3-4-2',
    mana: 3,
    attack: 4,
    health: 2,
    imageUrl: '/assets/cards/3-4-2.png',
  },
  {
    name: '3-4-3',
    mana: 3,
    attack: 4,
    health: 3,
    imageUrl: '/assets/cards/3-4-3.png',
  },
  {
    name: '4-1-3',
    mana: 4,
    attack: 1,
    health: 3,
    imageUrl: '/assets/cards/4-1-3.png',
  },
  {
    name: '4-2-4',
    mana: 4,
    attack: 2,
    health: 4,
    imageUrl: '/assets/cards/4-2-4.png',
  },
  {
    name: '4-2-8',
    mana: 4,
    attack: 2,
    health: 8,
    type: EnumTypeCard.taunt,
    imageUrl: '/assets/cards/4-2-8.png',
  },
  {
    name: '4-3-1',
    mana: 4,
    attack: 3,
    health: 1,
    imageUrl: '/assets/cards/4-3-1.png',
  },
  {
    name: '4-3-3_1',
    mana: 4,
    attack: 3,
    health: 3,
    imageUrl: '/assets/cards/4-3-3_1.png',
  },
  {
    name: '4-3-3',
    mana: 4,
    attack: 3,
    health: 3,
    imageUrl: '/assets/cards/4-3-3.png',
  },
  {
    name: '4-3-4',
    mana: 4,
    attack: 3,
    health: 4,
    imageUrl: '/assets/cards/4-3-4.png',
  },
  {
    name: '4-3-5',
    mana: 4,
    attack: 3,
    health: 5,
    type: EnumTypeCard.taunt,
    imageUrl: '/assets/cards/4-3-5.png',
  },
  {
    name: '4-4-3_1',
    mana: 4,
    attack: 4,
    health: 3,
    imageUrl: '/assets/cards/4-4-3_1.png',
  },
  {
    name: '4-4-3',
    mana: 4,
    attack: 4,
    health: 3,
    imageUrl: '/assets/cards/4-4-3.png',
  },
  {
    name: '4-4-4_1',
    mana: 4,
    attack: 4,
    health: 4,
    imageUrl: '/assets/cards/4-4-4_1.png',
  },
  {
    name: '4-4-4',
    mana: 4,
    attack: 4,
    health: 4,
    imageUrl: '/assets/cards/4-4-4.png',
  },
  {
    name: '5-2-6',
    mana: 5,
    attack: 2,
    health: 6,
    type: EnumTypeCard.taunt,
    imageUrl: '/assets/cards/5-2-6.png',
  },
  {
    name: '5-3-6_1',
    mana: 5,
    attack: 3,
    health: 6,
    type: EnumTypeCard.taunt,
    imageUrl: '/assets/cards/5-3-6_1.png',
  },
  {
    name: '5-3-6',
    mana: 5,
    attack: 3,
    health: 6,
    type: EnumTypeCard.taunt,
    imageUrl: '/assets/cards/5-3-6.png',
  },
  {
    name: '5-4-4',
    mana: 5,
    attack: 4,
    health: 4,
    imageUrl: '/assets/cards/5-4-4.png',
  },
  {
    name: '5-5-4',
    mana: 5,
    attack: 5,
    health: 4,
    imageUrl: '/assets/cards/5-5-4.png',
  },
  {
    name: '5-5-5',
    mana: 5,
    attack: 5,
    health: 5,
    type: EnumTypeCard.taunt,
    imageUrl: '/assets/cards/5-5-5.png',
  },
  {
    name: '6-3-4',
    mana: 6,
    attack: 3,
    health: 4,
    imageUrl: '/assets/cards/6-3-4.png',
  },
  {
    name: '6-4-6',
    mana: 6,
    attack: 4,
    health: 6,
    type: EnumTypeCard.taunt,
    imageUrl: '/assets/cards/6-4-6.png',
  },
  {
    name: '6-5-5',
    mana: 6,
    attack: 5,
    health: 5,
    type: EnumTypeCard.taunt,
    imageUrl: '/assets/cards/6-5-5.png',
  },
  {
    name: '6-5-6',
    mana: 6,
    attack: 5,
    health: 6,
    type: EnumTypeCard.taunt,
    imageUrl: '/assets/cards/6-5-6.png',
  },
  {
    name: '6-6-4',
    mana: 6,
    attack: 6,
    health: 4,
    imageUrl: '/assets/cards/6-6-4.png',
  },
]
